# Generated by Django 3.1.7 on 2021-04-27 12:59

import ads.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descr', models.CharField(max_length=100, verbose_name='decription')),
                ('phone_num', ads.models.PhoneNumberField(max_length=12, validators=[ads.models.PhoneNumberValidator], verbose_name='contact phone number')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='publication date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name="ad's category")),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['pub_date'], name='pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
    ]
