# Generated by Django 3.1.7 on 2021-04-23 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210423_2305'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date user joined'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('vote', models.IntegerField(blank=True, null=True, verbose_name='vote on movie')),
                ('text', models.TextField(blank=True, null=True, verbose_name='review text')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='review',
            field=models.ManyToManyField(through='users.Reviews', to='movies.Movie', verbose_name='list of watched movies'),
        ),
    ]
