# Generated by Django 3.1.7 on 2021-04-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210423_2305'),
        ('users', '0002_auto_20210423_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='review',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reviews',
            field=models.ManyToManyField(through='users.Review', to='movies.Movie'),
        ),
    ]
