# Generated by Django 3.1.7 on 2021-04-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210424_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
