# Generated by Django 3.1.7 on 2021-04-21 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('rel_date', models.DateField(verbose_name='release date')),
                ('producer', models.CharField(max_length=30)),
                ('descr', models.TextField(verbose_name='description')),
                ('rating', models.IntegerField(default=0)),
                ('poster', models.ImageField(default='movie_posters/no-poster.jpg', upload_to='movie_posters/')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='related genres')),
            ],
            options={
                'verbose_name_plural': 'movies',
                'ordering': ['rel_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('text', models.TextField(verbose_name='review text')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='related movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rel_date'], name='rel_date_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='rating_idx'),
        ),
    ]
