# Generated by Django 3.1.7 on 2021-04-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_users_reviews'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('vote__gte', 1), ('vote__lte', 10)), name='vote_constraint'),
        ),
    ]
