# Generated by Django 3.1.7 on 2021-04-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210424_0152'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='vote_constraint',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='rating_idx',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vote',
        ),
    ]
