# Generated by Django 3.1.7 on 2021-04-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210424_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users_reviews',
        ),
    ]
