# Generated by Django 3.1.7 on 2021-04-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_users_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
    ]
