# Generated by Django 3.1.7 on 2021-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default=1, verbose_name='review text'),
            preserve_default=False,
        ),
    ]
